version: "3.7"

services:
    client:
        container_name: client
        build:
            context: .
        volumes:
            - ./app:/app
            - /app/node_modules
        ports:
            - 4200:4200
        # command: tail -f /dev/null
        command: ng serve --disableHostCheck=true --host=0.0.0.0